### ISSUE TITLE
FACSvatar with Blender 3.3

### ISSUE THREAD

**Issue by Monika-cnb** [NumesSanguis/FACSvatar#36]
Hi Numes, 

I'm unable to run the FACSvatar_zeromq.py script from blender while the same script and pyzmq version works well with blender 2.79.

I'm getting the following error:
`Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/mon/FACSvatar/blender/facsvatar_zeromq.py", line 9, in <module>
    import zmq
  File "/home/mon/anaconda3/envs/blender_demo/lib/python3.5/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/home/mon/anaconda3/envs/blender_demo/lib/python3.5/site-packages/zmq/backend/cython/__init__.py)`

I've tried multiple things to resolve this but with no success.

Has anyone tried using FACSvatar visualization with newer versions of blender(3.3 or any other).

Please let me know if you're using FACSvatar with blender and which version of pyzmq??

Thanks

**Comment by NumesSanguis** [comment]
Hi Monika,
It is weird that this works in Blender 2.79, but not in 3.3 based on the error you pasted here. The Python version you use to run facsvatar_zeromq.py seems to be 3.5, but Blender 3.3 uses 3.10. That means that the wrong Python environment is being used.

More importantly though, you're using an older version of FACSvatar. The latest version is [FACSvatar v0.4.0](https://github.com/NumesSanguis/FACSvatar/tree/v0.4.0). This version relies for communication on a better working Blender addon (at least in Blender 2.83): [Blender-ZMQ-add-on](https://github.com/NumesSanguis/Blender-ZMQ-add-on).
This is my bad though. The master branch hasn't been updated to the latest version, because I wanted to polish it a bit more but then didn't have time to work on it anymore.

With the above version you should have better luck getting it to work with Blender. However, as I haven't touched this project for a while, I haven't been able to test it with Blender 3.3. Please let me know if you run into any issues with FACSvatar v0.4.0 and Blender-ZMQ-add-on.
